"""
Tests for idempotent View registration.

A View class can be safely registered on multiple parent routers (e.g. mounting
the same view under two different prefixes for back-compat, or registering on
both an admin app and a public app). The class-level preparation (schema
generation, endpoint annotation, dataclass __init__ setup) runs only once and
is reused across registrations; each registration produces its own APIRouter
mounted on the target parent. Re-registering a view on the SAME parent is a
no-op: each parent tracks the view classes already mounted on it.

Without the idempotency guard in ``_init_view_cls_and_add_to_router``,
registering the same View twice would:

* Re-rename endpoints (``create_endpoint`` → ``fooview_create_endpoint`` →
  ``fooview_fooview_create_endpoint``), yielding endpoint name collisions and
  broken signatures.
* Re-run ``_annotate`` on already-modified signatures.
* Re-trip ``_exclude_routes``: ``del view_func._api_route_args`` raises
  AttributeError on the second run, since the attribute was already removed.
* Risk corrupting the first registration's class attributes (``cls.schema``,
  ``cls.schema_create``, ``cls.schema_update``, ``cls.listing_param_schema``,
  ``cls.pagination_response_schema``).
"""

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy.orm import Mapped

import fastapi_restly as fr


def test_view_registered_on_two_apps_both_work(sync_db):
    """Register the same View on two separate FastAPI apps (e.g. an admin
    surface and a public surface) sharing the same backing model.

    Both registrations must answer end-to-end and persist into the same table.
    """
    engine, _ = sync_db

    class Gadget(fr.IDBase):
        name: Mapped[str]

    class GadgetSchema(fr.IDSchema):
        name: str

    class GadgetView(fr.RestView):
        prefix = "/gadgets"
        model = Gadget
        schema = GadgetSchema

    app_a = FastAPI()
    app_b = FastAPI()

    fr.include_view(app_a, GadgetView)
    fr.include_view(app_b, GadgetView)

    fr.DataclassBase.metadata.create_all(engine)

    client_a = TestClient(app_a)
    client_b = TestClient(app_b)

    # Both registrations accept POSTs.
    resp = client_a.post("/gadgets/", json={"name": "alpha"})
    assert resp.status_code == 201, resp.text
    assert resp.json()["name"] == "alpha"

    resp = client_b.post("/gadgets/", json={"name": "beta"})
    assert resp.status_code == 201, resp.text
    assert resp.json()["name"] == "beta"

    # Both registrations list — and they see the same rows because they share
    # the underlying SQLAlchemy table.
    items_a = client_a.get("/gadgets/").json()
    items_b = client_b.get("/gadgets/").json()
    names_a = sorted(item["name"] for item in items_a)
    names_b = sorted(item["name"] for item in items_b)
    assert names_a == names_b == ["alpha", "beta"]


def test_view_mounted_under_two_prefixes_via_subapp(sync_db):
    """Register a View on two sub-apps mounted under different prefixes within
    a single root app — a realistic back-compat pattern (``/v1`` and ``/v2``).
    """
    engine, _ = sync_db

    class Gizmo(fr.IDBase):
        name: Mapped[str]

    class GizmoSchema(fr.IDSchema):
        name: str

    class GizmoView(fr.RestView):
        prefix = "/gizmos"
        model = Gizmo
        schema = GizmoSchema

    sub_v1 = FastAPI()
    sub_v2 = FastAPI()
    fr.include_view(sub_v1, GizmoView)
    fr.include_view(sub_v2, GizmoView)

    root = FastAPI()
    root.mount("/v1", sub_v1)
    root.mount("/v2", sub_v2)

    fr.DataclassBase.metadata.create_all(engine)

    client = TestClient(root)
    resp = client.post("/v1/gizmos/", json={"name": "one"})
    assert resp.status_code == 201, resp.text
    resp = client.post("/v2/gizmos/", json={"name": "two"})
    assert resp.status_code == 201, resp.text

    names_v1 = sorted(item["name"] for item in client.get("/v1/gizmos/").json())
    names_v2 = sorted(item["name"] for item in client.get("/v2/gizmos/").json())
    assert names_v1 == names_v2 == ["one", "two"]


def test_class_attributes_are_not_corrupted_by_second_registration():
    """The schema/schema_create/schema_update/listing_param_schema generated by
    ``before_include_view`` survive a second registration unchanged.

    Before the idempotency guard, ``_init_all_endpoints`` would re-rename
    endpoints (e.g. ``widgetview_create_endpoint`` →
    ``widgetview_widgetview_create_endpoint``), corrupting the first
    registration's routing.
    """

    class Widget(fr.IDBase):
        title: Mapped[str]

    class WidgetSchema(fr.IDSchema):
        title: str

    class WidgetView(fr.RestView):
        prefix = "/widgets"
        model = Widget
        schema = WidgetSchema

    app_a = FastAPI()
    fr.include_view(app_a, WidgetView)

    # Snapshot the class attributes set by before_include_view.
    snapshot = {
        "schema": WidgetView.schema,
        "schema_create": WidgetView.schema_create,
        "schema_update": WidgetView.schema_update,
        "listing_param_schema": WidgetView.listing_param_schema,
    }
    # Snapshot endpoint names: _init_all_endpoints prefixes with the lowercased
    # class name, so e.g. WidgetView.create_endpoint.__name__ ==
    # "widgetview_create_endpoint". A second registration would prepend the
    # prefix again.
    endpoint_names = {
        name: getattr(WidgetView, name).__name__
        for name in (
            "get_many_endpoint",
            "get_one_endpoint",
            "create_endpoint",
            "update_endpoint",
            "delete_endpoint",
        )
    }

    # Second registration on a different parent must not error or mutate.
    app_b = FastAPI()
    fr.include_view(app_b, WidgetView)

    # All snapshot attributes must be the exact same objects.
    for attr, value in snapshot.items():
        assert getattr(WidgetView, attr) is value, (
            f"{attr} was replaced on the View class by the second registration"
        )

    # Endpoint names must not have been re-prefixed.
    for name, original_name in endpoint_names.items():
        assert getattr(WidgetView, name).__name__ == original_name, (
            f"endpoint {name!r} was renamed by the second registration: "
            f"{original_name!r} → {getattr(WidgetView, name).__name__!r}"
        )


def test_exclude_routes_does_not_crash_on_second_registration(sync_db):
    """``_exclude_routes`` removes ``_api_route_args`` from listed methods.

    Without the idempotency guard, a second registration would re-enter
    ``_exclude_routes`` and find the attribute already removed, raising
    AttributeError before the route would even mount.
    """
    engine, _ = sync_db

    class Token(fr.IDBase):
        name: Mapped[str]

    class TokenSchema(fr.IDSchema):
        name: str

    class TokenView(fr.RestView):
        prefix = "/tokens"
        model = Token
        schema = TokenSchema
        exclude_routes = ("delete_endpoint",)

    app_a = FastAPI()
    app_b = FastAPI()

    fr.include_view(app_a, TokenView)
    # This is the call that previously raised AttributeError.
    fr.include_view(app_b, TokenView)

    fr.DataclassBase.metadata.create_all(engine)

    # GET works on both, DELETE is excluded on both (404/405).
    client_a = TestClient(app_a)
    client_b = TestClient(app_b)
    assert client_a.get("/tokens/").status_code == 200
    assert client_b.get("/tokens/").status_code == 200
    assert client_a.delete("/tokens/1").status_code in (404, 405)
    assert client_b.delete("/tokens/1").status_code in (404, 405)


def test_subclass_of_registered_base_still_registers_independently(sync_db):
    """The idempotency marker is stored in ``cls.__dict__``, so a subclass of
    an already-registered base still goes through its own initialisation.

    Without ``__dict__.get`` semantics, subclasses would inherit the marker
    from the base and skip their own setup, so their endpoints would never be
    annotated/registered.
    """
    engine, _ = sync_db

    class Knob(fr.IDBase):
        label: Mapped[str]

    class KnobSchema(fr.IDSchema):
        label: str

    # Base view registered first…
    class KnobBase(fr.RestView):
        prefix = "/knobs"
        model = Knob
        schema = KnobSchema

    app_a = FastAPI()
    fr.include_view(app_a, KnobBase)

    # …then a subclass with its own prefix is registered separately.
    class FancyKnobView(KnobBase):
        prefix = "/fancy-knobs"

    app_b = FastAPI()
    fr.include_view(app_b, FancyKnobView)

    fr.DataclassBase.metadata.create_all(engine)

    client_a = TestClient(app_a)
    client_b = TestClient(app_b)

    resp = client_a.post("/knobs/", json={"label": "plain"})
    assert resp.status_code == 201, resp.text
    # FancyKnobView's prefix concatenates with the inherited "/knobs" base.
    resp = client_b.post("/knobs/fancy-knobs/", json={"label": "fancy"})
    assert resp.status_code == 201, resp.text


def _effective_route_pairs(app):
    """Yield ``(path, frozenset(methods))`` for every effective leaf route.

    FastAPI >=0.138 no longer flattens ``include_router`` into the parent: an
    included router appears in ``app.routes`` as an ``_IncludedRouter`` branch
    that resolves its concrete routes lazily. Expand those branches so route
    introspection sees view routes again; on older FastAPI the routes are
    already flat and pass straight through. The path-existence assertions below
    double as a guard that this expansion stays non-vacuous.
    """
    for route in app.routes:
        expand = getattr(route, "effective_route_contexts", None)
        leaves = expand() if expand is not None else (route,)
        for leaf in leaves:
            methods = getattr(leaf, "methods", None)
            path = getattr(leaf, "path", None)
            if methods and path is not None:
                yield path, frozenset(methods)


def _duplicate_routes(app):
    """Return {(path, methods): count} for any route registered more than once."""
    from collections import Counter

    counts = Counter(_effective_route_pairs(app))
    return {key: n for key, n in counts.items() if n > 1}


def test_subclass_and_parent_on_same_app_have_no_duplicate_routes(sync_db):
    """Regression for bug naa.

    Registering a base View AND a subclass of it on the SAME app must not
    duplicate the child's routes. Registering the base copies its CRUD
    endpoints into the base's ``__dict__``; walking the child's MRO then saw
    each endpoint twice (base original + base copy) and registered every child
    route x2. ``test_subclass_of_registered_base_still_registers_independently``
    above uses separate apps, so it never exercised the collision.
    """
    engine, _ = sync_db

    class Dial(fr.IDBase):
        label: Mapped[str]

    class DialSchema(fr.IDSchema):
        label: str

    class DialBase(fr.RestView):
        prefix = "/dials"
        model = Dial
        schema = DialSchema

    class FancyDialView(DialBase):
        prefix = "/fancy"

    app = FastAPI()
    fr.include_view(app, DialBase)
    fr.include_view(app, FancyDialView)

    assert _duplicate_routes(app) == {}

    paths = {path for path, _ in _effective_route_pairs(app)}
    # The child's CRUD routes exist (once) under the composed prefix.
    assert "/dials/fancy/" in paths
    assert "/dials/fancy/{id}" in paths

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    resp = client.post("/dials/fancy/", json={"label": "f"})
    assert resp.status_code == 201, resp.text


def test_inherited_custom_route_registered_once_on_same_app(sync_db):
    """A custom route declared on the base is inherited by a co-registered
    subclass exactly once (not duplicated)."""
    engine, _ = sync_db

    class Meter(fr.IDBase):
        label: Mapped[str]

    class MeterSchema(fr.IDSchema):
        label: str

    class MeterBase(fr.RestView):
        prefix = "/meters"
        model = Meter
        schema = MeterSchema

        @fr.get("/health")
        def health(self):
            return {"src": "base"}

    class SubMeterView(MeterBase):
        prefix = "/sub"

    app = FastAPI()
    fr.include_view(app, MeterBase)
    fr.include_view(app, SubMeterView)

    assert _duplicate_routes(app) == {}
    paths = {path for path, _ in _effective_route_pairs(app)}
    assert "/meters/health" in paths
    assert "/meters/sub/health" in paths

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.get("/meters/health").json() == {"src": "base"}
    assert client.get("/meters/sub/health").json() == {"src": "base"}


def test_subclass_route_override_wins_on_same_app(sync_db):
    """A subclass overriding an inherited custom route routes to its own
    version; the base keeps its own. No duplication, correct resolution."""
    engine, _ = sync_db

    class Lever(fr.IDBase):
        label: Mapped[str]

    class LeverSchema(fr.IDSchema):
        label: str

    class LeverBase(fr.RestView):
        prefix = "/levers"
        model = Lever
        schema = LeverSchema

        @fr.get("/health")
        def health(self):
            return {"src": "base"}

    class SubLeverView(LeverBase):
        prefix = "/sub"

        @fr.get("/health")
        def health(self):
            return {"src": "sub"}

    app = FastAPI()
    fr.include_view(app, LeverBase)
    fr.include_view(app, SubLeverView)

    assert _duplicate_routes(app) == {}

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.get("/levers/health").json() == {"src": "base"}
    assert client.get("/levers/sub/health").json() == {"src": "sub"}


def test_parent_exclude_routes_with_coregistered_subclass_does_not_crash(sync_db):
    """Regression for the exclude-routes interaction surfaced while fixing naa.

    A parent that excludes a route, co-registered with a subclass that inherits
    ``exclude_routes``, must register cleanly. The subclass inherits the
    exclusion (and never receives a routable copy of the excluded endpoint), so
    re-running ``_exclude_routes`` for the already-excluded name must be a
    no-op, not an ``AttributeError``. Both end up without the route; nothing is
    duplicated.
    """
    engine, _ = sync_db

    class Relay(fr.IDBase):
        label: Mapped[str]

    class RelaySchema(fr.IDSchema):
        label: str

    class RelayBase(fr.RestView):
        prefix = "/relays"
        model = Relay
        schema = RelaySchema
        exclude_routes = ("delete_endpoint",)

    class SubRelayView(RelayBase):
        prefix = "/sub"

    app = FastAPI()
    fr.include_view(app, RelayBase)
    fr.include_view(app, SubRelayView)  # previously raised AttributeError

    assert _duplicate_routes(app) == {}

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.get("/relays/").status_code == 200
    assert client.get("/relays/sub/").status_code == 200
    # delete is excluded on BOTH the parent and the subclass.
    assert client.delete("/relays/1").status_code in (404, 405)
    assert client.delete("/relays/sub/1").status_code in (404, 405)


def test_same_view_registered_twice_on_same_app_mounts_once(sync_db):
    """``include_view(app, V); include_view(app, V)`` on the SAME app used to
    mount V's routes twice (distinct from the base-plus-subclass duplication
    covered above): class preparation is guarded by ``_fr_initialised``, but
    every call still built a fresh APIRouter and ran ``include_router``. The
    second call must now be a no-op.
    """
    engine, _ = sync_db

    class Pulley(fr.IDBase):
        label: Mapped[str]

    class PulleySchema(fr.IDSchema):
        label: str

    class PulleyView(fr.RestView):
        prefix = "/pulleys"
        model = Pulley
        schema = PulleySchema

    app = FastAPI()
    fr.include_view(app, PulleyView)
    fr.include_view(app, PulleyView)

    assert _duplicate_routes(app) == {}
    paths = {path for path, _ in _effective_route_pairs(app)}
    assert "/pulleys/" in paths
    assert "/pulleys/{id}" in paths

    # Still answers end-to-end.
    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    resp = client.post("/pulleys/", json={"label": "p"})
    assert resp.status_code == 201, resp.text
    assert client.get("/pulleys/").status_code == 200


def test_same_view_registered_twice_on_same_router_mounts_once(sync_db):
    """The same-parent no-op also holds for APIRouter parents."""
    from fastapi import APIRouter

    engine, _ = sync_db

    class Crank(fr.IDBase):
        label: Mapped[str]

    class CrankSchema(fr.IDSchema):
        label: str

    class CrankView(fr.RestView):
        prefix = "/cranks"
        model = Crank
        schema = CrankSchema

    router = APIRouter()
    fr.include_view(router, CrankView)
    fr.include_view(router, CrankView)

    app = FastAPI()
    app.include_router(router)

    assert _duplicate_routes(app) == {}

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    resp = client.post("/cranks/", json={"label": "c"})
    assert resp.status_code == 201, resp.text


def test_same_app_noop_does_not_block_other_parents(sync_db):
    """The duplicate-registration no-op is scoped per parent: after a double
    registration on app A, registering on app B still mounts normally."""
    engine, _ = sync_db

    class Spring(fr.IDBase):
        label: Mapped[str]

    class SpringSchema(fr.IDSchema):
        label: str

    class SpringView(fr.RestView):
        prefix = "/springs"
        model = Spring
        schema = SpringSchema

    app_a = FastAPI()
    fr.include_view(app_a, SpringView)
    fr.include_view(app_a, SpringView)  # no-op

    app_b = FastAPI()
    fr.include_view(app_b, SpringView)

    assert _duplicate_routes(app_a) == {}
    assert _duplicate_routes(app_b) == {}

    fr.DataclassBase.metadata.create_all(engine)
    client_b = TestClient(app_b)
    resp = client_b.post("/springs/", json={"label": "s"})
    assert resp.status_code == 201, resp.text


def test_base_and_subclass_both_mount_on_same_app_despite_guard(sync_db):
    """The same-parent guard keys on the class object: a base and its subclass
    are distinct entries, so co-registering both on one app keeps working (the
    base-plus-subclass arrangement above), while re-registering either one is
    still a no-op."""
    engine, _ = sync_db

    class Cog(fr.IDBase):
        label: Mapped[str]

    class CogSchema(fr.IDSchema):
        label: str

    class CogBase(fr.RestView):
        prefix = "/cogs"
        model = Cog
        schema = CogSchema

    class FancyCogView(CogBase):
        prefix = "/fancy"

    app = FastAPI()
    fr.include_view(app, CogBase)
    fr.include_view(app, FancyCogView)
    fr.include_view(app, CogBase)  # no-op
    fr.include_view(app, FancyCogView)  # no-op

    assert _duplicate_routes(app) == {}
    paths = {path for path, _ in _effective_route_pairs(app)}
    assert "/cogs/" in paths
    assert "/cogs/fancy/" in paths

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.post("/cogs/", json={"label": "a"}).status_code == 201
    assert client.post("/cogs/fancy/", json={"label": "b"}).status_code == 201


def test_decorator_form_plus_explicit_call_is_noop(sync_db):
    """The changelog names this exact story: ``@fr.include_view(app)`` on the
    class combined with a later explicit ``fr.include_view(app, V)`` must not
    duplicate routes. Pins the decorator path against ever diverging from the
    call path."""
    engine, _ = sync_db

    class Belt(fr.IDBase):
        label: Mapped[str]

    class BeltSchema(fr.IDSchema):
        label: str

    app = FastAPI()

    @fr.include_view(app)
    class BeltView(fr.RestView):
        prefix = "/belts"
        model = Belt
        schema = BeltSchema

    fr.include_view(app, BeltView)

    assert _duplicate_routes(app) == {}

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.post("/belts/", json={"label": "b"}).status_code == 201


def test_app_and_its_router_count_as_one_parent(sync_db):
    """A FastAPI app delegates ``include_router`` to its ``.router``, so the
    two are aliases for one route table. The same-parent guard must treat them
    as one parent: mixing ``include_view(app, V)`` and
    ``include_view(app.router, V)`` mounts once, in either order."""
    engine, _ = sync_db

    class Gear(fr.IDBase):
        label: Mapped[str]

    class GearSchema(fr.IDSchema):
        label: str

    class GearView(fr.RestView):
        prefix = "/gears"
        model = Gear
        schema = GearSchema

    app = FastAPI()
    fr.include_view(app, GearView)
    fr.include_view(app.router, GearView)  # aliased parent → no-op
    fr.include_view(app, GearView)  # and back again → still a no-op

    assert _duplicate_routes(app) == {}
    paths = {path for path, _ in _effective_route_pairs(app)}
    assert "/gears/" in paths

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.post("/gears/", json={"label": "g"}).status_code == 201


def test_failed_registration_is_not_recorded_as_mounted(sync_db):
    """A registration that raises must not mark the view as mounted on the
    parent — otherwise a later, corrected ``include_view`` call would silently
    no-op and the app would serve no routes for the view at all. Pins the
    record-after-mount ordering in ``_init_view_cls_and_add_to_router``.

    (The retried registration currently re-runs endpoint renaming, so route
    *names*/operation IDs come out double-prefixed — a pre-existing prep
    re-entrancy bug, tracked separately; this test only asserts the routes
    mount and answer.)
    """
    engine, _ = sync_db

    class Winch(fr.IDBase):
        label: Mapped[str]

    class WinchSchema(fr.IDSchema):
        label: str

    class WinchView(fr.RestView):
        prefix = "/winches"
        model = Winch
        schema = WinchSchema
        exclude_routes = ("delete",)  # business name, not the route name

    app = FastAPI()
    with pytest.raises(AttributeError, match="not a route"):
        fr.include_view(app, WinchView)

    # Fix the mistake and retry on the SAME app: the failed attempt must not
    # have been recorded, so this call really mounts.
    WinchView.exclude_routes = ("delete_endpoint",)
    fr.include_view(app, WinchView)

    assert _duplicate_routes(app) == {}
    paths = {path for path, _ in _effective_route_pairs(app)}
    assert "/winches/" in paths

    fr.DataclassBase.metadata.create_all(engine)
    client = TestClient(app)
    assert client.post("/winches/", json={"label": "w"}).status_code == 201
    assert client.delete("/winches/1").status_code in (404, 405)


def test_exclude_routes_unknown_name_still_raises():
    """``exclude_routes`` listing a name that is no route anywhere in the
    lineage (e.g. the business-verb name ``get_one`` instead of the route name
    ``get_one_endpoint``) is a genuine mistake and still raises."""

    class Sprocket(fr.IDBase):
        label: Mapped[str]

    class SprocketSchema(fr.IDSchema):
        label: str

    class SprocketView(fr.RestView):
        prefix = "/sprockets"
        model = Sprocket
        schema = SprocketSchema
        exclude_routes = ("get_one",)  # business method, not the route name

    app = FastAPI()
    with pytest.raises(AttributeError, match="not a route"):
        fr.include_view(app, SprocketView)
