"""Project schema."""

from datetime import datetime

from pydantic import computed_field

import fastapi_restly as fr

from ..models import ProjectStatus


class ProjectSchema(fr.TimestampsSchemaMixin, fr.IDSchema):
    """Schema for Project model.

    Audit stamps (``created_by_id`` / ``updated_by_id``) and the
    denormalized roll-up (``total_story_points``) are marked ``ReadOnly``:
    they're populated server-side and the framework will refuse to copy
    them off a request body.
    """

    name: str
    slug: str = ""  # auto-generated by view if blank — see ProjectView.create
    description: str = ""
    status: ProjectStatus = ProjectStatus.ACTIVE
    deleted_at: datetime | None = None
    organization_id: int

    # Server-stamped — readonly so PATCH bodies can't spoof them.
    created_by_id: fr.ReadOnly[int | None] = None
    updated_by_id: fr.ReadOnly[int | None] = None

    # Denormalized roll-up — written by TaskView, not by the client.
    total_story_points: fr.ReadOnly[int] = 0

    # Transient response-only field — populated by get_one from permission state.
    can_edit: fr.ReadOnly[bool | None] = None

    # Computed fields - populated by the view, not stored in DB
    # Marked as ReadOnly so they're excluded from create/update
    task_count: fr.ReadOnly[int | None] = None
    completed_task_count: fr.ReadOnly[int | None] = None

    @computed_field
    @property
    def completion_percent(self) -> float | None:
        """Calculate completion percentage from task counts."""
        if self.task_count is None or self.task_count == 0:
            return None
        if self.completed_task_count is None:
            return 0.0
        return round((self.completed_task_count / self.task_count) * 100, 1)
