"""Upload model — illustrates the early-flush-for-PK pattern.

The brenntag/innovationlab codebase has a multipart-upload endpoint that
needs the parent ``Upload`` row's autogenerated primary key before it can
insert the related ``UploadLine`` rows. The flow is::

    upload = self.make_new_object(schema)
    await self.session.flush()        # populate upload.id
    upload.lines = [
        UploadLine(upload_id=upload.id, ...) for row in parsed_rows
    ]
    upload = await self.save_object(upload)   # final flush + refresh

This is the *one* canonical reason ``save_object`` and ``make_new_object``
both have to be public utilities (not just override override points) — the flow
needs two distinct flush points and a mutate step in between.
"""

from datetime import datetime

from sqlalchemy import ForeignKey, orm

import fastapi_restly as fr


class Upload(fr.TimestampsMixin, fr.IDBase):
    """Parent row for a batch of imported lines."""

    filename: orm.Mapped[str]
    organization_id: orm.Mapped[int] = orm.mapped_column(ForeignKey("organization.id"))
    uploaded_by_id: orm.Mapped[int | None] = orm.mapped_column(
        ForeignKey("user.id"), default=None
    )
    completed_at: orm.Mapped[datetime | None] = orm.mapped_column(default=None)
    line_count: orm.Mapped[int] = orm.mapped_column(default=0)

    lines: orm.Mapped[list["UploadLine"]] = orm.relationship(
        back_populates="upload", default_factory=list, cascade="all, delete-orphan"
    )


class UploadLine(fr.TimestampsMixin, fr.IDBase):
    """One parsed row from the uploaded file."""

    upload_id: orm.Mapped[int] = orm.mapped_column(ForeignKey("upload.id"))
    row_number: orm.Mapped[int]
    title: orm.Mapped[str]
    amount: orm.Mapped[int] = orm.mapped_column(default=0)

    upload: orm.Mapped["Upload"] = orm.relationship(back_populates="lines", init=False)
